apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-chart.frontend.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-chart.frontend.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-chart.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo-chart.frontend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: BACKEND_SERVICE_NAME
              value: {{ include "todo-chart.backend.fullname" . }}
            - name: BACKEND_SERVICE_PORT
              value: "{{ .Values.backend.service.port }}"
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chart.frontend.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-chart.frontend.labels" . | nindent 4 }}

spec:
  selector:
    {{- include "todo-chart.frontend.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  type: {{ .Values.frontend.service.type }}